### ISSUE TITLE
Bundle is incompatible with endroid/gcm

### ISSUE THREAD

**Issue by mschaffr** [endroid/EndroidGcmBundle#4]
Hi there,

since update of endroid/gcm to 1.2.4, this bundle seems to be not longer compatible. I get the issue that the class Endroid\Gcm\Client is not found.

I rolled back till endroid/gcm 1.2.3 and endroid/endroid-gcm-bundle 1.2.2. This is the last working version for me. It looks like the folder structure changes in endroid/gcm creates the issue.

I hope you're able to reproduce this bug.

Best regards

**Comment by endroid** [comment]
If you install version 1.2.7 of the bundle, it should automatically install version 1.2.5 of the library, which is compatible. What does your composer.json look like?

**Comment by mschaffr** [comment]
I'd used the master branch, but in any kind the problem has solved. Maybe a composer cache issue or something like that. So I'll use bundle version 1.2.* in future. Also a small misconfiguration by myself.

Everything works fine now, thanks for response.
