### ISSUE TITLE
sendTo return false if a registration token is passed

### ISSUE THREAD

**Issue by loryman** [endroid/EndroidGcmBundle#5]
When i get the ` endroid.gcm.client ` service and i call the function `sendTo` passing a registration id as the second argument, the response is always false.

I think the issue here is this piece of code:

    $message = json_decode($this->responses[0]->getContent(), true);
    if ($message === null || !array_key_exists('message_id', $message) || array_key_exists('failure', $message)) {
        return false;
    }

In particular `array_key_exists('failure', $message)` is always true because the response given by gcm is:

    {
      "multicast_id": 6986086116173756045,
      "success": 1,
      "failure": 0,
      "canonical_ids": 0,
      "results": [
        {
          "message_id": "0:1452868276277320%89dd68c1f9fd7ecd"
        }
      ]
    }

which has always the `failure` key

**Comment by endroid** [comment]
@loryman Please check version 1.1.12 to see if your issue is solved. The release refactors some of the code and removes the fragment you mentioned in favor of the existing validity check.

**Comment by enebe-nb** [comment]
After this solution, when sending a 'topic' message, the code breakes with:

Notice: Undefined property: stdClass::$success
500 Internal Server Error - ContextErrorException

Note: a topic message response only have 'message_id' as param.

If you only want to check if we get a successful request, why don't check the response code only?
200 = success
>400 = failure
