### ISSUE TITLE
Variable issue

### ISSUE THREAD

**Issue by ngydat** [endroid/EndroidGcmBundle#6]
Hello

In the usage section, there is this code :

`<?php
public function gcmSendAction()
{
    $client = $this->get('endroid.gcm.client');

    $registrationIds = array(
        // Registration ID's of devices to target
    );

    $data = array(
        'title' => 'Message title',
        'message' => 'Message body',
    );

    $response = $gcm->send($data, $registrationIds);

    ...
}`

Where does the gcm variable come from ?

**Comment by endroid** [comment]
Hi @ngydat the variable name was incorrect. It had to be $client. Thanks for noticing.
